(ns {{app-name}}.dev-inputs.sample-input)

(def dev-input-segments
  [{:name "Alberto" :age 20}
   {:name "Amee" :age 22}
   {:name "Stephani" :age 50}
   {:name "Nia" :age 42}
   {:name "Dane" :age 53}
   {:name "Angle" :age 12}
   {:name "Raleigh" :age 31}
   {:name "Doretha" :age 73}
   {:name "Jenni" :age 46}
   {:name "Charlene" :age 63}
   {:name "Madalyn" :age 36}
   {:name "Opal" :age 14}
   {:name "Bella" :age 19}
   {:name "Magaret" :age 22}
   {:name "Goldie" :age 24}
   {:name "Stepanie" :age 82}
   {:name "Amberly" :age 26}
   {:name "Hana" :age 37}
   {:name "Dalton" :age 63}
   {:name "Pasquale" :age 25}
   {:name "Anjelica" :age 53}
   {:name "Charley" :age 23}
   {:name "Arvilla" :age 41}
   {:name "Lannie" :age 39}
   {:name "Emelia" :age 34}
   {:name "Khalilah" :age 53}
   {:name "Rona" :age 16}
   {:name "Cary" :age 8}
   {:name "Fausto" :age 10}
   {:name "Gabriel" :age 70}
   {:name "Gavin" :age 62}
   {:name "Mercy" :age 35}
   {:name "Eliana" :age 27}
   {:name "Matha" :age 73}
   {:name "Alanna" :age 25}
   {:name "Erika" :age 21}
   {:name "Tambra" :age 22}
   {:name "Tonia" :age 43}
   {:name "Fredricka" :age 81}
   {:name "Bryant" :age 4}
   {:name "Zulema" :age 11}
   {:name "Savanna" :age 14}
   {:name "Rosette" :age 56}
   {:name "Wanda" :age 26}
   {:name "Suk" :age 38}
   {:name "Janean" :age 47}
   {:name "Kimberli" :age 49}
   {:name "Ailene" :age 12}
   {:name "Jan" :age 19}
   {:name "Arie" :age 24}])